apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: aivstore
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    replicated:
      size: 3
  gateway:
    port: 80
    instances: 1