# dev-tilt.yaml - Workshop Hub Development Deployment
# This sets up the hub, workshop namespace, and necessary network policies

# =============================================================================
# 1. Workshop Namespace
# =============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: workshops
  labels:
    name: workshops
    app.kubernetes.io/managed-by: tilt

---
# =============================================================================
# 2. ServiceAccount for Hub (in default namespace)
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-hub-sa
  namespace: default

---
# =============================================================================
# 3. Role for Hub (in workshops namespace)
# =============================================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workshop-manager-role
  namespace: workshops
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]

---
# =============================================================================
# 4. RoleBinding for Hub (in workshops namespace)
# =============================================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshop-manager-binding
  namespace: workshops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workshop-manager-role
subjects:
  - kind: ServiceAccount
    name: workshop-hub-sa
    namespace: default

---
# =============================================================================
# 5. Cilium Network Policy - Allow Hub to Workshop Namespace
# =============================================================================
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-hub-to-workshops
  namespace: workshops
spec:
  endpointSelector: {}
  ingress:
    # Allow traffic from hub namespace (default)
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: default
            app: workshop-hub
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "8888"
              protocol: TCP
    
    # Allow traffic from within workshops namespace (pod-to-pod)
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: workshops

---
# =============================================================================
# 6. Cilium Network Policy - Allow Workshops to External
# =============================================================================
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-workshops-egress
  namespace: workshops
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/managed-by: workshop-hub
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
    
    # Allow internet access
    - toEntities:
        - world
    
    # Allow pod-to-pod in same namespace
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: workshops

---
# =============================================================================
# 7. Cilium Network Policy - Allow Integration Tests
# =============================================================================
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-integration-tests
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app: workshop-integration-tests
  egress:
    # Allow tests to reach hub
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: default
            app: workshop-hub
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    
    # Allow tests to reach workshops
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: workshops
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "8888"
              protocol: TCP
    
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
    
    # Allow Kubernetes API access
    - toEntities:
        - kube-apiserver

---
# =============================================================================
# 8. Hub Deployment
# =============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-hub
  namespace: default
  labels:
    app: workshop-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-hub
  template:
    metadata:
      labels:
        app: workshop-hub
    spec:
      serviceAccountName: workshop-hub-sa
      containers:
        - name: workshop-hub
          image: workshop-hub:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            # Auth Config
            - name: HUB_AUTH_SIGNING_KEY
              value: "dev-secret-key-for-tilt-must-be-long-enough"
            
            # Logging
            - name: RUST_LOG
              value: "info,workshop_hub=debug"
            
            # Workshop Config
            - name: HUB_WORKSHOP_NAME
              value: "tilt-workshop"
            - name: HUB_WORKSHOP_NAMESPACE
              value: "workshops"
            - name: HUB_WORKSHOP_TTL_SECONDS
              value: "3600"
            - name: HUB_WORKSHOP_IDLE_SECONDS
              value: "600"
            - name: HUB_WORKSHOP_POD_LIMIT
              value: "10"
            
            # User Container Config
            - name: HUB_WORKSHOP_IMAGE
              value: "nginxdemos/hello:latest"
            - name: HUB_WORKSHOP_PORT
              value: "80"
            - name: HUB_WORKSHOP_CPU_REQUEST
              value: "50m"
            - name: HUB_WORKSHOP_CPU_LIMIT
              value: "200m"
            - name: HUB_WORKSHOP_MEM_REQUEST
              value: "64Mi"
            - name: HUB_WORKSHOP_MEM_LIMIT
              value: "128Mi"
            
            # Sidecar Config
            - name: HUB_WORKSHOP_SIDECAR_IMAGE
              value: "workshop-sidecar:dev"

---
# =============================================================================
# 9. Hub Service
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: workshop-hub-svc
  namespace: default
  labels:
    app: workshop-hub
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: workshop-hub

---
# =============================================================================
# 10. Secret for Integration Tests (JWT Secret)
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: workshop-hub-auth
  namespace: default
type: Opaque
stringData:
  jwt-secret: "dev-secret-key-for-tilt-must-be-long-enough"