# hosts/my-server/configuration.nix
{ config, pkgs, ... }:

{
  imports =
    [
      # Include the results of the hardware scan (generated by nixos-generate-config)
      ./hardware-configuration.nix
    ];

  # ==========================================
  # 1. Boot & System Basics
  # ==========================================
  
  # Use systemd-boot (UEFI). If you are using Legacy BIOS, swap this for grub.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "my-server";
  
  # CRITICAL: Required for ZFS. 
  # Generate a unique ID: `head -c4 /dev/urandom | od -A n -t x4`
  networking.hostId = "8425e349"; 

  # ==========================================
  # 2. ZFS & Storage Configuration
  # ==========================================
  
  # Enable ZFS kernel modules
  boot.supportedFilesystems = [ "zfs" ];
  
  # Auto-scrub the pool once a week to check for data corruption
  services.zfs.autoScrub.enable = true;

  # Mount the 2TB NVMe Storage Pool
  # Note: The OS drive mounting is handled in hardware-configuration.nix
  fileSystems."/mnt/data" = {
    device = "tank/share";
    fsType = "zfs";
    # Ensure it mounts after the ZFS module is ready
    options = [ "zfsutil" ]; 
  };

  # ==========================================
  # 3. Networking & Tailscale (The Security Layer)
  # ==========================================
  
  # Enable Tailscale
  services.tailscale = {
    enable = true;
    # Path to the file containing the reusable auth key (create this manually!)
    authKeyFile = "/var/keys/tailscale_key";
    # Allow magic SSH (optional, but convenient)
    extraUpFlags = [ "--ssh" ];
  };

  # FIREWALL RULES: The "Tailscale Only" Logic
  networking.firewall = {
    enable = true;
    
    # Trust everything coming from Tailscale
    trustedInterfaces = [ "tailscale0" ];
    
    # BLOCK port 22 on the physical LAN/WAN interface.
    # We leave 2049 open for NFS on the LAN if needed, but SSH is closed.
    allowedTCPPorts = [ 2049 ]; 
    allowedUDPPorts = [ ];
  };

  # ==========================================
  # 4. SSH Configuration
  # ==========================================
  
  services.openssh = {
    enable = true;
    
    # CRITICAL: Do NOT automatically open port 22 in the firewall.
    # We rely on 'trustedInterfaces = [ "tailscale0" ]' above to allow access.
    openFirewall = false;
    
    settings = {
      # Disable password login for security
      PasswordAuthentication = false;
      # Disable root login (force user login -> sudo)
      PermitRootLogin = "no";
    };
  };

  # ==========================================
  # 5. NFS Server Configuration
  # ==========================================
  
  services.nfs.server = {
    enable = true;
    # Define what to share and who can access it
    # '192.168.1.0/24' restricts NFS access to your local physical LAN.
    # NFS over Tailscale is possible but slow; usually better to keep NFS local.
    exports = ''
      /mnt/data 192.168.1.0/24(rw,nohide,insecure,no_subtree_check,no_root_squash)
    '';
  };

  # ==========================================
  # 6. User Account
  # ==========================================
  
  users.users.admin = {
    isNormalUser = true;
    extraGroups = [ "wheel" ]; # Enable 'sudo'
    
    # Add your personal public key here (for fallback access if MagicSSH fails)
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK..." 
    ];
  };

  # ==========================================
  # 7. Utilities
  # ==========================================
  environment.systemPackages = with pkgs; [
    vim
    git
    htop
    zfs # ZFS administration tools
  ];

  # Do not change this unless you know what you are doing
  system.stateVersion = "24.11"; 
}